# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand



test_that("check_plus_in_primary_fur_color works", {
  expect_equal(
    check_plus_in_primary_fur_color(primary_fur_color = c("Cinnamon", "Blue", "Yellow")),
    rep(TRUE, 3)
  )
  
  expect_equal(
    check_plus_in_primary_fur_color(primary_fur_color = c("Ciinamon+blue", "yellow")),
    c(FALSE, TRUE)
  )
})

test_that("check_plus_in_primary_fur_color does not works", {
  expect_error(
    check_plus_in_primary_fur_color(primary_fur_color = as.numeric(1,2,3))
  )
  

})
