# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand

test_that("get_df_nrows works", {
  expect_message(
    object = get_df_nrows(iris), 
    regexp = "The dataset is composed of 150 observations"
  ) 
})

test_that("get_df_nrows works", {
  expect_message(
    object = get_df_nrows(mtcars), 
    regexp = "The dataset is composed of 32 observations"
  ) 
})

test_that("get_df_nrows does not works", {
  expect_error(!all.equal(
    get_df_nrows(3),
    "The dataset is composed of 32 observation"
  )
)})
