# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("check_coordinates works", {
  expect_true(
    all.equal(
      check_coordinates(latitude = 42, longitude = 0),
      FALSE
    )
  )
  
  expect_true(
    all.equal(
      check_coordinates(latitude = 40.8, longitude = -73.95),
      TRUE
    )
  )
})

test_that("check_coordinates does not work", {
  expect_error(
    check_coordinates(latitude = "42", longitude = 0)
  ) 
  
  expect_error(
    check_coordinates(latitude = 42)
  ) 
})

