# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

#' Check the values of primary fur color
#'
#' @param primary_fur_color Character. A vector with the primary fur color.
#' @return a vector of logicals
#' @importFrom stringr str_detect
#' @export
#' @examples
#' check_plus_in_primary_fur_color(primary_fur_color = c("Cinnamon", "Blue", "Yellow"))
#' check_plus_in_primary_fur_color(primary_fur_color = c("Cinnamon", "Blue", NA))
#' check_plus_in_primary_fur_color(primary_fur_color = c("Cinnamon", "Blue", 3))
#' check_plus_in_primary_fur_color(primary_fur_color = c("Ciinamon+blue", "yellow"))
check_plus_in_primary_fur_color <- function(primary_fur_color) {
  
  if (!is.character(primary_fur_color)) {
    stop(paste0("Argument ", primary_fur_color, " is not character"))
  }
  
  colors_are_ok <- !str_detect(string = primary_fur_color, pattern = "\\+")
  return(colors_are_ok)
}
