# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand


#' get nrows of input df
#'
#' @param df a datframe for which one wants to know the number of rows
#' @importFrom glue glue
#' @return a message indicating the number of rows hold by the df
#' @export
#'
#' @examples
#' get_df_nrows(iris)
#' get_df_nrows(mtcars)
get_df_nrows <- function(df) {
  nrow_df <- nrow(df)
  message(glue("The dataset is composed of {nrow_df} observations"))
}
